name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a 'master' si es el nombre de tu rama principal

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Esto soluciona el Warning

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v2
        with:
          version: 8 # O la versión que prefieras

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies 🔧
        run: pnpm install

      - name: Build 🏗️
        run: pnpm run build
        env: 
            VITE_BASE_URL: ${{secrets.VITE_BASE_URL}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # La carpeta que genera Vite
          branch: gh-pages # Rama donde se subirá el contenido estático